version: '3.7'

services:
  db:
    image: postgres:9.6-alpine
    healthcheck:
      test: pg_isready || exit 1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 8432:5432
