# Generated by Django 2.2.13 on 2021-07-01 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import src.core.models


def generate_credentials(apps, schema_editor):

    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_token', models.CharField(default=functools.partial(src.core.models.get_random_string, *(), **{'length': 16}), max_length=255)),
                ('auth_token', models.CharField(default=functools.partial(src.core.models.get_random_string, *(), **{'length': 16}), max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(generate_credentials),
    ]
