# Generated by Django 2.2.13 on 2021-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210809_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubstaffAccessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(max_length=32)),
                ('expires_in', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
