# Generated by Django 2.2.13 on 2021-12-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hubstaffaccessinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubstaffaccessinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
