SYNONYMS = {
    "auth": ["authentication", "login", "signin"],
    "me": ["self", "myself"],
    "users": ["user", "users", "employee", "employees", "account", "accounts", "member", "members", "staff", "people"],
    "projects": ["task", "tasks", "subprojects", "subproject"],
    "organizations": ["organization", "institution", "company", "companies", "groups"],
    "integrations": ["connection", "connections", "setup", "setups"],
    "last_activity": ["activity", "activities", "action", "actions", "last"],
    "members": ["staff_member", "staff_members", "persons", "users"],
    "links": ["integrations", "connectivity"],
    "activities": ["activity", "actions", "action", "operations", "operation", "work", "working"],
    "last_activities": ["activity", "actions", "action", "operations", "operation", "work", "working"],
    "applications": ["application", "app", "apps"],
    "application_activities": ["application-activities", "app_activities", "app-activities"],
    "daily": ["by_day", "day"],
    "url_activities": ["url-activities", "link_activities", "link-activities"],
    "urls": ["url", "link", "links"],
    "screenshots": ["shots", "screens", "images"],
    "notes": ["memos", "data"],
    "tasks": ["todos", "task"],
    "weekly": ["by_week", "week", "weeks", "seven_days"],
    "my": ["own", "me", "myself", "i"],
    "team": ["members", "team_members", "staff"],
    "custom": ["specific", "advanced"],
    "by_project": ["projects", "group_by_project", "project"],
    "by_member": ["members", "member", "group_by_member"],
    "by_date": ["date", "dates", "days", "day", "daily"],
    "time_edit_logs": ["time_logs", "edit_logs"],
    "team_payments": ["earnings", "money"],
    "update_metadata": ["metadata_update", "set_metadata"],
    "update_members": ["members_update", "set_members"],
    "invites": ["invitations"],
    "clients": ["client"],
    "locations": ["location", "loc"],
    "client_invoices": ["client-invoices"],
    "team_invoices": ["team-invoices"],
    "time_off_policies": ["time-off-policies"],
    "time_off_requests": ["time-off-requests"],
    "attendance_schedules": ["attendance"],
    "holidays": ["rest"],
    "job_sites": ["job-sites"],
    "timesheets": ["time_sheets", "time-sheets", "time"],
    "attendance_shifts": ["shifts"],
    "budget_histories": ["budget", "budget-history"],
    "integration_links": ["integrations"],
    "user_links": ["user-links", "userlinks"],
    "project_links": ["project-links", "projectlinks"],
}
